# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0017_auto_20180308_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='svn_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='svn\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='historicalappmodel',
            name='svn_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='svn\u5730\u5740'),
        ),
    ]
